export {default as Home} from './Home/Home'
export {default as SignIn} from './SignIn/SignIn'
export {default as Register} from './Register/Register'
export {default as Resume} from './Resume/Resume'
export {default as Dashboard } from './Dashboard/Dashboard'
export {default as Technicians } from './Technicians/Technicians'
export {default as StarRating } from './Star-Rating/StarRating'